### ISSUE TITLE
CLI to specify classroom and assignment by name, not ID

### ISSUE THREAD

**Issue by NukeManDan** [github/gh-classroom#56] opened 2023-11-02 01:44 UTC
**Is your feature request related to a problem? Please describe.**
I would like to use the CLI tool to operate on a specific assignment without needing to lookup it's ID or use the interactive CLI selector. This is to use the CLI in a non-interactive environment (for me, wrapping this CLI in another tool).

**Describe the solution you'd like**
A CLI command that will do best effort in trying to get an assignment from a string, searching all your classrooms. If there is no unique match, error with possible matches and the string to use them. This would also imply a classroom might need to be passed in as an argument as well, and if present, would restrict matching the assignment name to that classroom only (this classroom identified by a string matcher as well).

**Describe alternatives you've considered**
Multistep manual and interactive process using the CLI to gather the ID of the assignment by hand to pass into the final classroom CLI command (as there is no machine readable output from the classroom CLI).

**Additional context**
Related to #55

**Comment by colematt** [comment] 2024-01-08 21:24
Possible duplicate of #3 ?

**Comment by nixpad** [comment] 2024-02-23 15:37
Closing as mentioned above, this is a duplicate of https://github.com/github/gh-classroom/issues/3

**Closed by nixpad** 2024-02-23 15:37 UTC
Labels: enhancement
